# -*- coding: utf-8 -*-
"""Kaggle_Integrador.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JU0UqAdX04appMZoCj0_7qkncafits2g

# Data Analisys
"""

import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns

# Ruta de Acceso
DATA_DIR = "/content/drive/MyDrive/Esteban/Estudio/Maestria Arquitectura/Semestre I/Diseño y Optimización de Bases de Datos/Proyecto Integrador - Ecommify/Kaggle_Dataset"

# Montar Drive
from google.colab import drive
drive.mount("/content/drive", force_remount=True)

# Diccionario para guardar los DataFrames
tables = {}
for file in os.listdir(DATA_DIR):
    if file.endswith('.csv'):
        name = file.replace('olist_', '').replace('_dataset.csv', '').replace('.csv', '')
        tables[name] = pd.read_csv(os.path.join(DATA_DIR, file))
        print(f"Tabla cargada: {name}")


from collections import defaultdict

col_map = defaultdict(list)
for name, df in tables.items():
    for col in df.columns:
        col_map[col].append(name)

print("--- Posibles Relaciones Detectadas ---")
for col, tabs in col_map.items():
    if len(tabs) > 1:
        print(f"Columna '{col}' conecta las tablas: {tabs}")


# Analizar nulos en todas las tablas cargadas
for nombre, df in tables.items():
    print(f"\n--- Datos faltantes en: {nombre} ---")
    nulos = df.isnull().sum()
    print(nulos[nulos > 0]) # Solo muestra las columnas que tienen nulos


customers_df = pd.read_csv(os.path.join(DATA_DIR, "olist_customers_dataset.csv"))
orders_df = pd.read_csv(os.path.join(DATA_DIR, "olist_orders_dataset.csv"))


# Estructura técnica
print("--- Información General de Órdenes ---")
print(orders_df.info())

# Estadísticas descriptivas
print("\n--- Resumen Estadístico de Órdenes ---")
display(orders_df.describe(include='all'))

print("Valores nulos por columna en Órdenes:")
print(orders_df.isnull().sum())

# Porcentaje de nulos
nulos_pct = (orders_df.isnull().sum() / len(orders_df)) * 100
print("\nPorcentaje de nulos:")
print(nulos_pct)

# Visualización Geográfica (Distribución de Clientes)
plt.figure(figsize=(12, 6))
sns.countplot(data=customers_df, x='customer_state', order=customers_df['customer_state'].value_counts().index)
plt.title('Distribución Geográfica de Clientes por Estado')
plt.xlabel('Estado')
plt.ylabel('Cantidad de Clientes')
plt.show()


# Convertir a datetime
orders_df['order_purchase_timestamp'] = pd.to_datetime(orders_df['order_purchase_timestamp'])

# Graficar órdenes por mes
orders_df.set_index('order_purchase_timestamp').resample('M').size().plot(figsize=(12,6), color='teal', marker='o')
plt.title('Evolución Temporal de Compras (Mensual)')
plt.ylabel('Número de Órdenes')
plt.grid(True)
plt.show()



# 3. Leer archivos y contar registros
conteo_datos = {}

for archivo in os.listdir(DATA_DIR):
    if archivo.endswith('.csv'): # Puedes cambiar a .xlsx si es necesario
        path_completo = os.path.join(DATA_DIR, archivo)
        try:
            # Cargamos solo una columna para que sea más rápido
            df = pd.read_csv(path_completo, usecols=[0])
            conteo_datos[archivo] = len(df)
        except:
            print(f"Error al leer {archivo}")

# 4. Ordenar de menor a mayor
conteo_ordenado = dict(sorted(conteo_datos.items(), key=lambda item: item[1]))

# 5. Crear la gráfica
plt.figure(figsize=(12, 6))
plt.bar(conteo_ordenado.keys(), conteo_ordenado.values(), color='#3498db')
plt.xlabel('Datasets')
plt.ylabel('Número de Registros')
plt.title('Comparativa: Cantidad de datos por Dataset (Ascendente)')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""# Generate Data Files for SQL Postgress"""

!pip install pandas
!pip install numpy

import pandas as pd
import os
import json
import matplotlib.pyplot as plt
import seaborn as sns

# Ruta de Acceso
DATA_DIR = "/content/drive/MyDrive/Esteban/Estudio/Maestria Arquitectura/Semestre I/Diseño y Optimización de Bases de Datos/Proyecto Integrador - Ecommify/Kaggle_Dataset"

# Montar Drive
from google.colab import drive
drive.mount("/content/drive", force_remount=True)

customers = pd.read_csv(os.path.join(DATA_DIR,'olist_customers_dataset.csv'))
geolocation = pd.read_csv(os.path.join(DATA_DIR,'olist_geolocation_dataset.csv'))
order_items = pd.read_csv(os.path.join(DATA_DIR,'olist_order_items_dataset.csv'))
payments = pd.read_csv(os.path.join(DATA_DIR,'olist_order_payments_dataset.csv'))
reviews = pd.read_csv(os.path.join(DATA_DIR,'olist_order_reviews_dataset.csv'))
orders = pd.read_csv(os.path.join(DATA_DIR,'olist_orders_dataset.csv'))
products = pd.read_csv(os.path.join(DATA_DIR,'olist_products_dataset.csv'))
sellers = pd.read_csv(os.path.join(DATA_DIR,'olist_sellers_dataset.csv'))
translation = pd.read_csv(os.path.join(DATA_DIR,'product_category_name_translation.csv'))


#Transformación PostgreSQL
#Customers
customers_pg = pd.DataFrame()

customers_pg['customer_id'] = customers['customer_id']
customers_pg['customer_unique_id'] = customers['customer_unique_id']

customers_pg['customer_address'] = customers.apply(
    lambda row: f'({row.customer_zip_code_prefix},"{row.customer_city}","{row.customer_state}")',
    axis=1
)

output_path = os.path.join(DATA_DIR, 'pg_customers.csv')
customers_pg.to_csv(output_path, index=False)
print(f"¡Archivo customers_pg guardado exitosamente en: {output_path}!")


geolocation_pg = pd.DataFrame()

geolocation_pg['geolocation_zip_code_prefix'] = geolocation['geolocation_zip_code_prefix']

geolocation_pg['wkt_point'] = geolocation.apply(
    lambda row: f'POINT({row.geolocation_lng} {row.geolocation_lat})',
    axis=1
)

geolocation_pg['geolocation_city'] = geolocation['geolocation_city']
geolocation_pg['geolocation_state'] = geolocation['geolocation_state']

#geolocation_pg.to_csv('pg_geolocation.csv', index=False)

output_path = os.path.join(DATA_DIR, 'pg_geolocation.csv')
geolocation_pg.to_csv(output_path, index=False)
print(f"¡Archivo pg_geolocation guardado exitosamente en: {output_path}!")


products_pg = pd.DataFrame()

products_pg['product_id'] = products['product_id']
products_pg['product_category_name'] = products['product_category_name']

products_pg['product_specifications'] = products.apply(
    lambda row: json.dumps({
        'weight_g': row.get('product_weight_g'),
        'length_cm': row.get('product_length_cm'),
        'height_cm': row.get('product_height_cm'),
        'width_cm': row.get('product_width_cm'),
        'photos_qty': row.get('product_photos_qty')
    }),
    axis=1
)

products_pg['product_photos'] = '{}'

#products_pg.to_csv('pg_products.csv', index=False)
output_path = os.path.join(DATA_DIR, 'products_pg.csv')
products_pg.to_csv(output_path, index=False)
print(f"¡Archivo products_pg guardado exitosamente en: {output_path}!")


sellers_pg = pd.DataFrame()

sellers_pg['seller_id'] = sellers['seller_id']

sellers_pg['seller_address'] = sellers.apply(
    lambda row: f'({row.seller_zip_code_prefix},"{row.seller_city}","{row.seller_state}")',
    axis=1
)

#sellers_pg.to_csv('pg_sellers.csv', index=False)
output_path = os.path.join(DATA_DIR, 'sellers_pg.csv')
sellers_pg.to_csv(output_path, index=False)
print(f"¡Archivo sellers_pg guardado exitosamente en: {output_path}!")



orders_pg = pd.DataFrame()

orders_pg['order_id'] = orders['order_id']
orders_pg['customer_id'] = orders['customer_id']
orders_pg['order_status'] = orders['order_status']

orders_pg['order_logistics_timeline'] = orders.apply(
    lambda row: f'[{row.order_purchase_timestamp},{row.order_delivered_customer_date}]',
    axis=1
)

orders_pg['order_estimated_delivery'] = orders['order_estimated_delivery_date']

#orders_pg.to_csv('pg_orders.csv', index=False)
output_path = os.path.join(DATA_DIR, 'orders_pg.csv')
orders_pg.to_csv(output_path, index=False)
print(f"¡Archivo orders_pg guardado exitosamente en: {output_path}!")


payment_grouped = payments.groupby('order_id').apply(
    lambda x: x.to_dict(orient='records')
).to_dict()

order_details_pg = pd.DataFrame()

order_details_pg['order_item_id'] = order_items.index + 1
order_details_pg['order_id'] = order_items['order_id']
order_details_pg['product_id'] = order_items['product_id']
order_details_pg['seller_id'] = order_items['seller_id']
order_details_pg['price'] = order_items['price']
order_details_pg['freight_value'] = order_items['freight_value']

order_details_pg['payment_details'] = order_items['order_id'].apply(
    lambda oid: json.dumps(payment_grouped.get(oid, []))
)

#order_details_pg.to_csv('pg_order_details.csv', index=False)
output_path = os.path.join(DATA_DIR, 'order_details_pg.csv')
order_details_pg.to_csv(output_path, index=False)
print(f"¡Archivo order_details_pg guardado exitosamente en: {output_path}!")


#Transformación MongoDB



reviews_summary = reviews.groupby('review_id').agg({
    'review_score': ['mean', 'count']
})

reviews_summary.columns = ['avg_score', 'total_reviews']
reviews_summary = reviews_summary.reset_index()


catalog_products = []

for _, row in products.iterrows():

    doc = {
        '_id': row['product_id'],
        'category': row['product_category_name'],

        'active_promotions': {
            'is_promo': False,
            'discount': 0,
            'valid_until': None
        },

        'attributes': {
            'weight_g': row.get('product_weight_g'),
            'dimensions': {
                'length': row.get('product_length_cm'),
                'height': row.get('product_height_cm'),
                'width': row.get('product_width_cm')
            }
        },

        'media': [],

        'reviews_summary': {
            'avg_score': 0,
            'total_reviews': 0
        }
    }

    catalog_products.append(doc)



    with open('mongo_catalog_products.json', 'w') as f:
      json.dump(catalog_products, f, indent=4)


    customer_sessions = []

for _, row in customers.iterrows():

    session_doc = {
        '_id': row['customer_unique_id'],
        'customer_id': row['customer_id'],
        'last_activity': None,
        'active_cart': {
            'items': [],
            'total': 0
        }
    }

    customer_sessions.append(session_doc)



    with open('mongo_customer_sessions.json', 'w') as f:
      json.dump(customer_sessions, f, indent=4)

"""Generate Mongo DB Json Files"""

# =========================================================
# GENERACIÓN DE ARCHIVOS JSON PARA MONGODB
# GOOGLE COLAB
# =========================================================

# =========================================================
# 1. IMPORTAR LIBRERÍAS
# =========================================================

import pandas as pd
import json
import os

# =========================================================
# 2. MONTAR GOOGLE DRIVE
# =========================================================

from google.colab import drive
drive.mount("/content/drive", force_remount=True)

# =========================================================
# 3. RUTA DE ACCESO
# =========================================================

DATA_DIR = "/content/drive/MyDrive/Esteban/Estudio/Maestria Arquitectura/Semestre I/Diseño y Optimización de Bases de Datos/Proyecto Integrador - Ecommify/Kaggle_Dataset"

# =========================================================
# 4. LEER CSV ORIGINALES
# =========================================================

customers = pd.read_csv(
    os.path.join(DATA_DIR, 'olist_customers_dataset.csv')
)

geolocation = pd.read_csv(
    os.path.join(DATA_DIR, 'olist_geolocation_dataset.csv')
)

order_items = pd.read_csv(
    os.path.join(DATA_DIR, 'olist_order_items_dataset.csv')
)

payments = pd.read_csv(
    os.path.join(DATA_DIR, 'olist_order_payments_dataset.csv')
)

reviews = pd.read_csv(
    os.path.join(DATA_DIR, 'olist_order_reviews_dataset.csv')
)

orders = pd.read_csv(
    os.path.join(DATA_DIR, 'olist_orders_dataset.csv')
)

products = pd.read_csv(
    os.path.join(DATA_DIR, 'olist_products_dataset.csv')
)

sellers = pd.read_csv(
    os.path.join(DATA_DIR, 'olist_sellers_dataset.csv')
)

print("CSV cargados correctamente")

# =========================================================
# 5. LIMPIAR VALORES NULOS
# =========================================================

customers = customers.fillna("")
products = products.fillna("")
orders = orders.fillna("")
reviews = reviews.fillna("")
payments = payments.fillna("")
order_items = order_items.fillna("")
sellers = sellers.fillna("")
geolocation = geolocation.fillna("")

print("Valores nulos limpiados")

# =========================================================
# =========================================================
# COLECCIÓN 1:
# catalog_products_collection
# =========================================================
# =========================================================

print("Generando catalog_products_collection...")

catalog_products = []

products_records = products.to_dict(orient='records')

for row in products_records:

    document = {

        "_id": row["product_id"],

        "category": row["product_category_name"],

        "active_promotions": {
            "is_promo": False,
            "discount": 0,
            "valid_until": None
        },

        "attributes": {

            "weight_g": row["product_weight_g"],

            "dimensions": {
                "length_cm": row["product_length_cm"],
                "height_cm": row["product_height_cm"],
                "width_cm": row["product_width_cm"]
            },

            "photos_qty": row["product_photos_qty"]
        },

        "media": [],

        "reviews_summary": {
            "avg_score": 0,
            "total_reviews": 0
        }
    }

    catalog_products.append(document)

print(f"Productos Mongo generados: {len(catalog_products)}")

# =========================================================
# 6. EXPORTAR JSON PRODUCTS
# =========================================================

PRODUCTS_OUTPUT = os.path.join(
    DATA_DIR,
    "mongo_catalog_products.json"
)

with open(PRODUCTS_OUTPUT, "w", encoding="utf-8") as f:

    json.dump(
        catalog_products,
        f,
        ensure_ascii=False,
        indent=4
    )

print("mongo_catalog_products.json generado")

# =========================================================
# =========================================================
# COLECCIÓN 2:
# customer_sessions_collection
# =========================================================
# =========================================================

print("Generando customer_sessions_collection...")

customer_sessions = []

customers_records = customers.to_dict(orient='records')

for row in customers_records:

    session_document = {

        "_id": row["customer_unique_id"],

        "customer_id": row["customer_id"],

        "last_activity": None,

        "active_cart": {

            "items": [],

            "total": 0
        }
    }

    customer_sessions.append(session_document)

print(f"Sesiones Mongo generadas: {len(customer_sessions)}")

# =========================================================
# 7. EXPORTAR JSON SESSIONS
# =========================================================

SESSIONS_OUTPUT = os.path.join(
    DATA_DIR,
    "mongo_customer_sessions.json"
)

with open(SESSIONS_OUTPUT, "w", encoding="utf-8") as f:

    json.dump(
        customer_sessions,
        f,
        ensure_ascii=False,
        indent=4
    )

print("mongo_customer_sessions.json generado")

# =========================================================
# 8. FINALIZACIÓN
# =========================================================

print("========================================")
print("PROCESO COMPLETADO")
print("========================================")

print("Archivos generados:")

print(PRODUCTS_OUTPUT)

print(SESSIONS_OUTPUT)

print("========================================")
print("Listos para importar en MongoDB Atlas")
print("========================================")