# -*- coding: utf-8 -*-
"""Kaggle_Integrador.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JU0UqAdX04appMZoCj0_7qkncafits2g

# Data Analisys

**bold text**# New Section
"""

import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns

# Ruta de Acceso
DATA_DIR = "/content/drive/MyDrive/Esteban/Estudio/Maestria Arquitectura/Semestre I/Diseño y Optimización de Bases de Datos/Proyecto Integrador - Ecommify/Kaggle_Dataset"

# Montar Drive
from google.colab import drive
drive.mount("/content/drive", force_remount=True)

# Diccionario para guardar los DataFrames
tables = {}
for file in os.listdir(DATA_DIR):
    if file.endswith('.csv'):
        name = file.replace('olist_', '').replace('_dataset.csv', '').replace('.csv', '')
        tables[name] = pd.read_csv(os.path.join(DATA_DIR, file))
        print(f"Tabla cargada: {name}")


from collections import defaultdict

col_map = defaultdict(list)
for name, df in tables.items():
    for col in df.columns:
        col_map[col].append(name)

print("--- Posibles Relaciones Detectadas ---")
for col, tabs in col_map.items():
    if len(tabs) > 1:
        print(f"Columna '{col}' conecta las tablas: {tabs}")


# Analizar nulos en todas las tablas cargadas
for nombre, df in tables.items():
    print(f"\n--- Datos faltantes en: {nombre} ---")
    nulos = df.isnull().sum()
    print(nulos[nulos > 0]) # Solo muestra las columnas que tienen nulos


customers_df = pd.read_csv(os.path.join(DATA_DIR, "olist_customers_dataset.csv"))
orders_df = pd.read_csv(os.path.join(DATA_DIR, "olist_orders_dataset.csv"))


# Estructura técnica
print("--- Información General de Órdenes ---")
print(orders_df.info())

# Estadísticas descriptivas
print("\n--- Resumen Estadístico de Órdenes ---")
display(orders_df.describe(include='all'))

print("Valores nulos por columna en Órdenes:")
print(orders_df.isnull().sum())

# Porcentaje de nulos
nulos_pct = (orders_df.isnull().sum() / len(orders_df)) * 100
print("\nPorcentaje de nulos:")
print(nulos_pct)

# Visualización Geográfica (Distribución de Clientes)
plt.figure(figsize=(12, 6))
sns.countplot(data=customers_df, x='customer_state', order=customers_df['customer_state'].value_counts().index)
plt.title('Distribución Geográfica de Clientes por Estado')
plt.xlabel('Estado')
plt.ylabel('Cantidad de Clientes')
plt.show()


# Convertir a datetime
orders_df['order_purchase_timestamp'] = pd.to_datetime(orders_df['order_purchase_timestamp'])

# Graficar órdenes por mes
orders_df.set_index('order_purchase_timestamp').resample('M').size().plot(figsize=(12,6), color='teal', marker='o')
plt.title('Evolución Temporal de Compras (Mensual)')
plt.ylabel('Número de Órdenes')
plt.grid(True)
plt.show()



# 3. Leer archivos y contar registros
conteo_datos = {}

for archivo in os.listdir(DATA_DIR):
    if archivo.endswith('.csv'): # Puedes cambiar a .xlsx si es necesario
        path_completo = os.path.join(DATA_DIR, archivo)
        try:
            # Cargamos solo una columna para que sea más rápido
            df = pd.read_csv(path_completo, usecols=[0])
            conteo_datos[archivo] = len(df)
        except:
            print(f"Error al leer {archivo}")

# 4. Ordenar de menor a mayor
conteo_ordenado = dict(sorted(conteo_datos.items(), key=lambda item: item[1]))

# 5. Crear la gráfica
plt.figure(figsize=(12, 6))
plt.bar(conteo_ordenado.keys(), conteo_ordenado.values(), color='#3498db')
plt.xlabel('Datasets')
plt.ylabel('Número de Registros')
plt.title('Comparativa: Cantidad de datos por Dataset (Ascendente)')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""# Generate Data Files for SQL Postgress"""

!pip install pandas
!pip install numpy

import pandas as pd
import os
import json
import matplotlib.pyplot as plt
import seaborn as sns

# Ruta de Acceso
DATA_DIR = "/content/drive/MyDrive/Esteban/Estudio/Maestria Arquitectura/Semestre I/Diseño y Optimización de Bases de Datos/Proyecto Integrador - Ecommify/Kaggle_Dataset"

# Montar Drive
from google.colab import drive
drive.mount("/content/drive", force_remount=True)

customers = pd.read_csv(os.path.join(DATA_DIR,'olist_customers_dataset.csv'))
geolocation = pd.read_csv(os.path.join(DATA_DIR,'olist_geolocation_dataset.csv'))
order_items = pd.read_csv(os.path.join(DATA_DIR,'olist_order_items_dataset.csv'))
payments = pd.read_csv(os.path.join(DATA_DIR,'olist_order_payments_dataset.csv'))
reviews = pd.read_csv(os.path.join(DATA_DIR,'olist_order_reviews_dataset.csv'))
orders = pd.read_csv(os.path.join(DATA_DIR,'olist_orders_dataset.csv'))
products = pd.read_csv(os.path.join(DATA_DIR,'olist_products_dataset.csv'))
sellers = pd.read_csv(os.path.join(DATA_DIR,'olist_sellers_dataset.csv'))
translation = pd.read_csv(os.path.join(DATA_DIR,'product_category_name_translation.csv'))


#Transformación PostgreSQL
#Customers
customers_pg = pd.DataFrame()

customers_pg['customer_id'] = customers['customer_id']
customers_pg['customer_unique_id'] = customers['customer_unique_id']

customers_pg['customer_address'] = customers.apply(
    lambda row: f'({row.customer_zip_code_prefix},"{row.customer_city}","{row.customer_state}")',
    axis=1
)

output_path = os.path.join(DATA_DIR, 'pg_customers.csv')
customers_pg.to_csv(output_path, index=False)
print(f"¡Archivo customers_pg guardado exitosamente en: {output_path}!")


geolocation_pg = pd.DataFrame()

geolocation_pg['geolocation_zip_code_prefix'] = geolocation['geolocation_zip_code_prefix']

geolocation_pg['wkt_point'] = geolocation.apply(
    lambda row: f'POINT({row.geolocation_lng} {row.geolocation_lat})',
    axis=1
)

geolocation_pg['geolocation_city'] = geolocation['geolocation_city']
geolocation_pg['geolocation_state'] = geolocation['geolocation_state']

#geolocation_pg.to_csv('pg_geolocation.csv', index=False)

output_path = os.path.join(DATA_DIR, 'pg_geolocation.csv')
geolocation_pg.to_csv(output_path, index=False)
print(f"¡Archivo pg_geolocation guardado exitosamente en: {output_path}!")


products_pg = pd.DataFrame()

products_pg['product_id'] = products['product_id']
products_pg['product_category_name'] = products['product_category_name']

products_pg['product_specifications'] = products.apply(
    lambda row: json.dumps({
        'weight_g': row.get('product_weight_g'),
        'length_cm': row.get('product_length_cm'),
        'height_cm': row.get('product_height_cm'),
        'width_cm': row.get('product_width_cm'),
        'photos_qty': row.get('product_photos_qty')
    }),
    axis=1
)

products_pg['product_photos'] = '{}'

#products_pg.to_csv('pg_products.csv', index=False)
output_path = os.path.join(DATA_DIR, 'products_pg.csv')
products_pg.to_csv(output_path, index=False)
print(f"¡Archivo products_pg guardado exitosamente en: {output_path}!")


sellers_pg = pd.DataFrame()

sellers_pg['seller_id'] = sellers['seller_id']

sellers_pg['seller_address'] = sellers.apply(
    lambda row: f'({row.seller_zip_code_prefix},"{row.seller_city}","{row.seller_state}")',
    axis=1
)

#sellers_pg.to_csv('pg_sellers.csv', index=False)
output_path = os.path.join(DATA_DIR, 'sellers_pg.csv')
sellers_pg.to_csv(output_path, index=False)
print(f"¡Archivo sellers_pg guardado exitosamente en: {output_path}!")



orders_pg = pd.DataFrame()

orders_pg['order_id'] = orders['order_id']
orders_pg['customer_id'] = orders['customer_id']
orders_pg['order_status'] = orders['order_status']

orders_pg['order_logistics_timeline'] = orders.apply(
    lambda row: f'[{row.order_purchase_timestamp},{row.order_delivered_customer_date}]',
    axis=1
)

orders_pg['order_estimated_delivery'] = orders['order_estimated_delivery_date']

#orders_pg.to_csv('pg_orders.csv', index=False)
output_path = os.path.join(DATA_DIR, 'orders_pg.csv')
orders_pg.to_csv(output_path, index=False)
print(f"¡Archivo orders_pg guardado exitosamente en: {output_path}!")


payment_grouped = payments.groupby('order_id').apply(
    lambda x: x.to_dict(orient='records')
).to_dict()

order_details_pg = pd.DataFrame()

order_details_pg['order_item_id'] = order_items.index + 1
order_details_pg['order_id'] = order_items['order_id']
order_details_pg['product_id'] = order_items['product_id']
order_details_pg['seller_id'] = order_items['seller_id']
order_details_pg['price'] = order_items['price']
order_details_pg['freight_value'] = order_items['freight_value']

order_details_pg['payment_details'] = order_items['order_id'].apply(
    lambda oid: json.dumps(payment_grouped.get(oid, []))
)

#order_details_pg.to_csv('pg_order_details.csv', index=False)
output_path = os.path.join(DATA_DIR, 'order_details_pg.csv')
order_details_pg.to_csv(output_path, index=False)
print(f"¡Archivo order_details_pg guardado exitosamente en: {output_path}!")


#Transformación MongoDB



reviews_summary = reviews.groupby('review_id').agg({
    'review_score': ['mean', 'count']
})

reviews_summary.columns = ['avg_score', 'total_reviews']
reviews_summary = reviews_summary.reset_index()


catalog_products = []

for _, row in products.iterrows():

    doc = {
        '_id': row['product_id'],
        'category': row['product_category_name'],

        'active_promotions': {
            'is_promo': False,
            'discount': 0,
            'valid_until': None
        },

        'attributes': {
            'weight_g': row.get('product_weight_g'),
            'dimensions': {
                'length': row.get('product_length_cm'),
                'height': row.get('product_height_cm'),
                'width': row.get('product_width_cm')
            }
        },

        'media': [],

        'reviews_summary': {
            'avg_score': 0,
            'total_reviews': 0
        }
    }

    catalog_products.append(doc)



    with open('mongo_catalog_products.json', 'w') as f:
      json.dump(catalog_products, f, indent=4)


    customer_sessions = []

for _, row in customers.iterrows():

    session_doc = {
        '_id': row['customer_unique_id'],
        'customer_id': row['customer_id'],
        'last_activity': None,
        'active_cart': {
            'items': [],
            'total': 0
        }
    }

    customer_sessions.append(session_doc)



    with open('mongo_customer_sessions.json', 'w') as f:
      json.dump(customer_sessions, f, indent=4)

"""Generate Mongo DB Json Files"""

# =========================================================
# GENERACIÓN DE ARCHIVOS JSON PARA MONGODB
# GOOGLE COLAB
# =========================================================

# =========================================================
# 1. IMPORTAR LIBRERÍAS
# =========================================================

import pandas as pd
import json
import os

# =========================================================
# 2. MONTAR GOOGLE DRIVE
# =========================================================

from google.colab import drive
drive.mount("/content/drive", force_remount=True)

# =========================================================
# 3. RUTA DE ACCESO
# =========================================================

DATA_DIR = "/content/drive/MyDrive/Esteban/Estudio/Maestria Arquitectura/Semestre I/Diseño y Optimización de Bases de Datos/Proyecto Integrador - Ecommify/Kaggle_Dataset"

# =========================================================
# 4. LEER CSV ORIGINALES
# =========================================================

customers = pd.read_csv(
    os.path.join(DATA_DIR, 'olist_customers_dataset.csv')
)

geolocation = pd.read_csv(
    os.path.join(DATA_DIR, 'olist_geolocation_dataset.csv')
)

order_items = pd.read_csv(
    os.path.join(DATA_DIR, 'olist_order_items_dataset.csv')
)

payments = pd.read_csv(
    os.path.join(DATA_DIR, 'olist_order_payments_dataset.csv')
)

reviews = pd.read_csv(
    os.path.join(DATA_DIR, 'olist_order_reviews_dataset.csv')
)

orders = pd.read_csv(
    os.path.join(DATA_DIR, 'olist_orders_dataset.csv')
)

products = pd.read_csv(
    os.path.join(DATA_DIR, 'olist_products_dataset.csv')
)

sellers = pd.read_csv(
    os.path.join(DATA_DIR, 'olist_sellers_dataset.csv')
)

print("CSV cargados correctamente")

# =========================================================
# 5. LIMPIAR VALORES NULOS
# =========================================================

customers = customers.fillna("")
products = products.fillna("")
orders = orders.fillna("")
reviews = reviews.fillna("")
payments = payments.fillna("")
order_items = order_items.fillna("")
sellers = sellers.fillna("")
geolocation = geolocation.fillna("")

print("Valores nulos limpiados")

# =========================================================
# =========================================================
# COLECCIÓN 1:
# catalog_products_collection
# =========================================================
# =========================================================

print("Generando catalog_products_collection...")

catalog_products = []

products_records = products.to_dict(orient='records')

for row in products_records:

    document = {

        "_id": row["product_id"],

        "category": row["product_category_name"],

        "active_promotions": {
            "is_promo": False,
            "discount": 0,
            "valid_until": None
        },

        "attributes": {

            "weight_g": row["product_weight_g"],

            "dimensions": {
                "length_cm": row["product_length_cm"],
                "height_cm": row["product_height_cm"],
                "width_cm": row["product_width_cm"]
            },

            "photos_qty": row["product_photos_qty"]
        },

        "media": [],

        "reviews_summary": {
            "avg_score": 0,
            "total_reviews": 0
        }
    }

    catalog_products.append(document)

print(f"Productos Mongo generados: {len(catalog_products)}")

# =========================================================
# 6. EXPORTAR JSON PRODUCTS
# =========================================================

PRODUCTS_OUTPUT = os.path.join(
    DATA_DIR,
    "mongo_catalog_products.json"
)

with open(PRODUCTS_OUTPUT, "w", encoding="utf-8") as f:

    json.dump(
        catalog_products,
        f,
        ensure_ascii=False,
        indent=4
    )

print("mongo_catalog_products.json generado")

# =========================================================
# =========================================================
# COLECCIÓN 2:
# customer_sessions_collection
# =========================================================
# =========================================================

print("Generando customer_sessions_collection...")

customer_sessions = []

customers_records = customers.to_dict(orient='records')

for row in customers_records:

    session_document = {

        "_id": row["customer_unique_id"],

        "customer_id": row["customer_id"],

        "last_activity": None,

        "active_cart": {

            "items": [],

            "total": 0
        }
    }

    customer_sessions.append(session_document)

print(f"Sesiones Mongo generadas: {len(customer_sessions)}")

# =========================================================
# 7. EXPORTAR JSON SESSIONS
# =========================================================

SESSIONS_OUTPUT = os.path.join(
    DATA_DIR,
    "mongo_customer_sessions.json"
)

with open(SESSIONS_OUTPUT, "w", encoding="utf-8") as f:

    json.dump(
        customer_sessions,
        f,
        ensure_ascii=False,
        indent=4
    )

print("mongo_customer_sessions.json generado")

# =========================================================
# 8. FINALIZACIÓN
# =========================================================

print("========================================")
print("PROCESO COMPLETADO")
print("========================================")

print("Archivos generados:")

print(PRODUCTS_OUTPUT)

print(SESSIONS_OUTPUT)

print("========================================")
print("Listos para importar en MongoDB Atlas")
print("========================================")

"""# Verificación de Conectividad mediante Escritura NoSQL
# Conexión desde Google Colab a MongoDB

### Objetivo:
Validar de extremo a extremo (End-to-End) la capacidad de escritura en el clúster remoto `ClusterOlistKaggle` alojado en MongoDB Atlas desde el entorno de cómputo efímero de Google Colab.

### Mecanismo de Validación:
1. **Instanciación:** Se apunta el cliente de PyMongo a la base de datos objetivo `DataBaseOlistKaggle`.
2. **Creación Dinámica:** Debido a la naturaleza *schemaless* (sin esquema rígido) de MongoDB, las bases de datos y colecciones no requieren un comando `CREATE`. Se crean automáticamente en el servidor en el momento exacto en que reciben su primer documento.
3. **Persistencia:** Se inserta un documento de metadatos del proyecto en una colección de auditoría interna llamada `control_conexiones`.
4. **Confirmación:** Se captura y despliega el identificador único universal (`_id` / ObjectId) generado por el motor de base de datos para confirmar que el registro fue persistido en el almacenamiento en la nube.

"""

!pip install pymongo dnspython -q

import pymongo
print("Versión de PyMongo instalada:", pymongo.__version__)

from google.colab import userdata
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi


from google.colab import userdata


# 1. Recuperar la cadena de conexión de forma segura desde los secretos de Colab
try:
    uri = userdata.get('MONGO_URI')
except Exception:
    raise ValueError("No se encontró el secreto 'MONGO_URI'. Asegúrate de configurarlo en el icono de la llave lateral.")

# 2. Inicializar el cliente utilizando la Stable API de MongoDB
client = MongoClient(uri, server_api=ServerApi('1'))

# 3. Realizar un test de conexión (Ping) al clúster para validar la arquitectura de red
try:
    client.admin.command('ping')
    print("🚀 ¡Conexión establecida con éxito al clúster 'ClusterOlistKaggle'!")

    # Listar los sistemas de archivos o bases de datos iniciales
    print("📂 Bases de datos detectadas en Atlas:", client.list_database_names())
except Exception as error:
    print("❌ Error de infraestructura o autenticación al intentar conectar:")
    print(error)




import datetime
from google.colab import userdata
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

# 1. Recuperar la URI segura desde tus secretos de Colab
uri = userdata.get('MONGO_URI')
client = MongoClient(uri, server_api=ServerApi('1'))

# 2. Apuntar a tu Base de Datos del proyecto
db = client['DataBaseOlistKaggle']

# 3. Definir la colección de pruebas / auditoría
coleccion_auditoria = db['control_conexiones']

# 4. Estructurar el documento JSON/BSON de prueba
documento_verificacion = {
    "entorno_origen": "Google Colab VM",
    "maestria": "Arquitectura de Software",
    "materia": "Bases de Datos No Relacionales",
    "timestamp_utc": datetime.datetime.now(datetime.timezone.utc),
    "prueba_estado": "Exitosa",
    "detalles": {
        "driver": "PyMongo",
        "cluster_destino": "ClusterOlistKaggle"
    }
}

# 5. Intentar realizar la escritura física en MongoDB Atlas
print("Iniciando escritura de prueba en la nube...")
try:
    resultado = coleccion_auditoria.insert_one(documento_verificacion)

    print("\n=======================================================")
    print("  ✅ VERIFICACIÓN DE CONECTIVIDAD TOTALMENTE COMPLETA  ")
    print("=======================================================")
    print(f"• Estado: Base de datos y colección validadas con éxito.")
    print(f"• Colección creada/afectada: '{coleccion_auditoria.name}'")
    print(f"• ID único generado en la Nube (ObjectId): {resultado.inserted_id}")
    print("=======================================================\n")

except Exception as e:
    print("\n=======================================================")
    print("  ❌ FALLO EN LA OPERACIÓN DE ESCRITURA (WRITE ERROR)  ")
    print("=======================================================")
    print(f"Error detectado: {e}")
    print("=======================================================\n")

"""# Índice de Concentración (HHI)

# Evaluar distribución geográfica de sellers y su impacto
"""

import os
import pandas as pd
from google.colab import drive

# 1. Asegurar el montaje de Google Drive
drive.mount('/content/drive', force_remount=True)

# 2. Configurar Rutas provistas en tu entorno
DATA_DIR = "/content/drive/MyDrive/Esteban/Estudio/Maestria Arquitectura/Semestre I/Diseño y Optimización de Bases de Datos/Proyecto Integrador - Ecommify/Kaggle_Dataset"

ruta_sellers = os.path.join(DATA_DIR, "olist_sellers_dataset.csv")
ruta_items = os.path.join(DATA_DIR, "olist_order_items_dataset.csv")

try:
    # 3. Cargar los datasets reales utilizando Pandas
    print("Cargando fuentes de datos geográficas para análisis NoSQL...")
    df_sellers = pd.read_csv(ruta_sellers)
    df_items = pd.read_csv(ruta_items)

    # 4. Cruzar datos para asociar a cada producto del catálogo el estado de su vendedor
    df_merged = pd.merge(df_items, df_sellers, on='seller_id', how='inner')

    # 5. Agrupación por Estado del Vendedor ('seller_state') para evaluar la densidad del catálogo
    df_geo_nosql = df_merged.groupby('seller_state').agg(
        Productos_En_Catalogo=('product_id', 'count')
    ).reset_index()

    total_productos_catalogo = df_geo_nosql['Productos_En_Catalogo'].sum()

    # 6. Calcular la cuota porcentual de impacto (Market Share %) en el catálogo NoSQL
    df_geo_nosql['Participacion_%'] = (df_geo_nosql['Productos_En_Catalogo'] / total_productos_catalogo) * 100

    # 7. Algoritmo del Índice de Herfindahl-Hirschman (HHI) Geográfico NoSQL
    df_geo_nosql['Cuadrado_Participacion'] = df_geo_nosql['Participacion_%'] ** 2
    hhi_geo_nosql = df_geo_nosql['Cuadrado_Participacion'].sum()

    # =================================================================
    #       DESPLIEGUE DEL REPORTE DE INFRAESTRUCTURA DE CATÁLOGO
    # =================================================================
    print("\n" + "="*75)
    print("   REEVALUACIÓN GEOGRÁFICA NoSQL: DENSIDAD DE CATÁLOGO (Ecommify)  ")
    print("="*75)
    print(f"• Volumen Total de Productos en el Catálogo Activo: {total_productos_catalogo:,}")
    print(f"• Estados Federados que alimentan el Catálogo NoSQL: {len(df_geo_nosql)}")
    print(f"• ÍNDICE HHI GEOGRÁFICO REAL (NoSQL): {hhi_geo_nosql:.2f}\n")

    print("--- TOP 5 ESTADOS QUE DETERMINAN LA CARGA DE ESCRITURA EN EL CLÚSTER ---")
    print(df_geo_nosql.sort_values(by='Participacion_%', ascending=False)[
        ['seller_state', 'Productos_En_Catalogo', 'Participacion_%']
    ].head(5).to_string(index=False))
    print("-"*73 + "\n")

    print("--- EVALUACIÓN DE ARQUITECTURA DISTRIBUIDA (SHARDING) ---")
    if hhi_geo_nosql > 2500:
        print("🔴 DIAGNÓSTICO: CONCENTRACIÓN GEOGRÁFICA CRÍTICA EN EL ORIGEN DEL CATÁLOGO.")
        print("   Riesgo Técnico NoSQL: El estado de São Paulo (SP) monopoliza la inyección de ítems.")
        print("   Si intentaras segmentar o fragmentar el catálogo de productos utilizando la ubicación")
        print("   geográfica del vendedor como Shard Key, causarías un HOTSPOT DE ESCRITURA CRÍTICO")
        print("   en el Shard asignado a la región 'SP' durante cargas masivas o actualizaciones de stock.")
        print("   ")
        print("   Solución Arquitectónica: Reconfirmar el descarte de claves geográficas y mantener")
        print("   la Compound Shard Key '{ category: 1, _id: 1 }' para el catálogo de productos.")
    else:
        print("🟢 DIAGNÓSTICO: Distribución Geográfica Homogénea.")
    print("="*75)

except Exception as e:
    print(f"❌ Ocurrió un fallo en el procesamiento de datos: {e}")

# Implementación y validación

!pip install "pymongo[srv]" dnspython -q

import random
import datetime
from bson import ObjectId
from google.colab import userdata
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

# 1. Conexión segura usando secretos de Colab
uri = userdata.get("MONGO_URI")

if not uri:
    raise ValueError("No se encontró el secreto MONGO_URI. Configúralo en Google Colab > Secrets.")

client = MongoClient(uri, server_api=ServerApi("1"))
client.admin.command("ping")

print("Conexión exitosa a MongoDB Atlas")

# 2. Base de datos y colecciones
db = client["DataBaseOlistKaggle"]
products = db["products"]
reviews = db["reviews"]

# Limpieza opcional para repetir la prueba
products.delete_many({})
reviews.delete_many({})

print("Colecciones limpias y listas para insertar datos.")

# Generación de 1000 productos con esquema flexible

categorias = ["electronics", "home", "fashion", "sports", "books"]

def generar_specifications(categoria):
    if categoria == "electronics":
        return {
            "brand": random.choice(["Sony", "Samsung", "Apple", "Lenovo", "Xiaomi"]),
            "model": f"MOD-{random.randint(1000, 9999)}",
            "battery_life_hours": random.choice([8, 12, 24, 30, 40]),
            "warranty_months": random.choice([12, 24, 36])
        }

    elif categoria == "home":
        return {
            "material": random.choice(["Madera", "Metal", "Vidrio", "Plástico"]),
            "dimensions_cm": {
                "length": random.randint(20, 200),
                "width": random.randint(20, 120),
                "height": random.randint(10, 180)
            },
            "weight_kg": round(random.uniform(1.0, 30.0), 2)
        }

    elif categoria == "fashion":
        return {
            "size": random.choice(["XS", "S", "M", "L", "XL"]),
            "color": random.choice(["Negro", "Blanco", "Azul", "Rojo", "Verde"]),
            "material": random.choice(["Algodón", "Poliéster", "Cuero", "Lino"])
        }

    elif categoria == "sports":
        return {
            "sport_type": random.choice(["Fútbol", "Ciclismo", "Running", "Tenis"]),
            "professional_use": random.choice([True, False]),
            "weight_kg": round(random.uniform(0.2, 15.0), 2)
        }

    elif categoria == "books":
        return {
            "author": random.choice(["Autor A", "Autor B", "Autor C", "Autor D"]),
            "pages": random.randint(100, 900),
            "language": random.choice(["Español", "Inglés", "Portugués"]),
            "format": random.choice(["Físico", "Digital"])
        }

productos = []

for i in range(1000):
    categoria = random.choice(categorias)

    producto = {
        "name": f"Producto {i + 1}",
        "category": categoria,
        "price": round(random.uniform(10.0, 1500.0), 2),
        "seller_id": f"SELLER-{random.randint(1, 80)}",
        "stock": random.randint(0, 500),
        "created_at": datetime.datetime.now(datetime.timezone.utc),

        # Subdocumento flexible/polimórfico
        "specifications": generar_specifications(categoria),

        # Computed Pattern
        "metrics": {
            "total_units_sold": random.randint(0, 1000),
            "average_rating": 0,
            "total_reviews": 0
        },

        # Embedding ligero para consulta rápida en catálogo
        "reviews_summary": {
            "average_rating": 0,
            "total_reviews": 0
        }
    }

    productos.append(producto)

resultado_productos = products.insert_many(productos)

print(f"Productos insertados: {len(resultado_productos.inserted_ids)}")

# Generación de 1000 productos con esquema flexible

categorias = ["electronics", "home", "fashion", "sports", "books"]

def generar_specifications(categoria):
    if categoria == "electronics":
        return {
            "brand": random.choice(["Sony", "Samsung", "Apple", "Lenovo", "Xiaomi"]),
            "model": f"MOD-{random.randint(1000, 9999)}",
            "battery_life_hours": random.choice([8, 12, 24, 30, 40]),
            "warranty_months": random.choice([12, 24, 36])
        }

    elif categoria == "home":
        return {
            "material": random.choice(["Madera", "Metal", "Vidrio", "Plástico"]),
            "dimensions_cm": {
                "length": random.randint(20, 200),
                "width": random.randint(20, 120),
                "height": random.randint(10, 180)
            },
            "weight_kg": round(random.uniform(1.0, 30.0), 2)
        }

    elif categoria == "fashion":
        return {
            "size": random.choice(["XS", "S", "M", "L", "XL"]),
            "color": random.choice(["Negro", "Blanco", "Azul", "Rojo", "Verde"]),
            "material": random.choice(["Algodón", "Poliéster", "Cuero", "Lino"])
        }

    elif categoria == "sports":
        return {
            "sport_type": random.choice(["Fútbol", "Ciclismo", "Running", "Tenis"]),
            "professional_use": random.choice([True, False]),
            "weight_kg": round(random.uniform(0.2, 15.0), 2)
        }

    elif categoria == "books":
        return {
            "author": random.choice(["Autor A", "Autor B", "Autor C", "Autor D"]),
            "pages": random.randint(100, 900),
            "language": random.choice(["Español", "Inglés", "Portugués"]),
            "format": random.choice(["Físico", "Digital"])
        }

productos = []

for i in range(1000):
    categoria = random.choice(categorias)

    producto = {
        "name": f"Producto {i + 1}",
        "category": categoria,
        "price": round(random.uniform(10.0, 1500.0), 2),
        "seller_id": f"SELLER-{random.randint(1, 80)}",
        "stock": random.randint(0, 500),
        "created_at": datetime.datetime.now(datetime.timezone.utc),

        # Subdocumento flexible/polimórfico
        "specifications": generar_specifications(categoria),

        # Computed Pattern
        "metrics": {
            "total_units_sold": random.randint(0, 1000),
            "average_rating": 0,
            "total_reviews": 0
        },

        # Embedding ligero para consulta rápida en catálogo
        "reviews_summary": {
            "average_rating": 0,
            "total_reviews": 0
        }
    }

    productos.append(producto)

resultado_productos = products.insert_many(productos)

print(f"Productos insertados: {len(resultado_productos.inserted_ids)}")

# Crear colección reviews como referencia externa

productos_insertados = list(products.find({}, {"_id": 1, "name": 1}))

reviews_docs = []

for producto in productos_insertados:
    cantidad_reviews = random.randint(0, 8)

    for _ in range(cantidad_reviews):
        review = {
            "product_id": producto["_id"],  # referencia externa
            "customer_id": f"CUSTOMER-{random.randint(1, 500)}",
            "rating": random.randint(1, 5),
            "comment": random.choice([
                "Excelente producto",
                "Buena relación calidad/precio",
                "Cumple con lo esperado",
                "Podría mejorar",
                "No era lo que esperaba"
            ]),
            "created_at": datetime.datetime.now(datetime.timezone.utc)
        }

        reviews_docs.append(review)

if reviews_docs:
    resultado_reviews = reviews.insert_many(reviews_docs)
    print(f"Reviews insertadas: {len(resultado_reviews.inserted_ids)}")
else:
    print("No se generaron reviews.")

# Actualizar métricas pre-calculadas con Computed Pattern

pipeline_metricas = [
    {
        "$group": {
            "_id": "$product_id",
            "average_rating": {"$avg": "$rating"},
            "total_reviews": {"$sum": 1}
        }
    }
]

metricas = list(reviews.aggregate(pipeline_metricas))

for metrica in metricas:
    products.update_one(
        {"_id": metrica["_id"]},
        {
            "$set": {
                "metrics.average_rating": round(metrica["average_rating"], 2),
                "metrics.total_reviews": metrica["total_reviews"],
                "reviews_summary.average_rating": round(metrica["average_rating"], 2),
                "reviews_summary.total_reviews": metrica["total_reviews"]
            }
        }
    )

print(f"Métricas actualizadas para {len(metricas)} productos.")

# Índices recomendados para mejorar rendimiento

products.create_index("category")
products.create_index("price")
products.create_index("seller_id")
products.create_index("metrics.average_rating")
reviews.create_index("product_id")
reviews.create_index("rating")

print("Índices creados correctamente.")

# Consultas funcionales del catálogo

print("Consulta 1: productos de electrónica con precio menor a 500")
consulta_1 = list(products.find(
    {
        "category": "electronics",
        "price": {"$lt": 500}
    },
    {
        "_id": 0,
        "name": 1,
        "category": 1,
        "price": 1,
        "specifications.brand": 1,
        "reviews_summary": 1
    }
).limit(5))

for doc in consulta_1:
    print(doc)


print("\nConsulta 2: productos mejor calificados")
consulta_2 = list(products.find(
    {
        "metrics.total_reviews": {"$gte": 3}
    },
    {
        "_id": 0,
        "name": 1,
        "category": 1,
        "price": 1,
        "metrics": 1
    }
).sort("metrics.average_rating", -1).limit(10))

for doc in consulta_2:
    print(doc)

# Aggregation pipeline: ranking por categoría

pipeline_ranking_categoria = [
    {
        "$group": {
            "_id": "$category",
            "total_products": {"$sum": 1},
            "avg_price": {"$avg": "$price"},
            "avg_rating": {"$avg": "$metrics.average_rating"},
            "total_units_sold": {"$sum": "$metrics.total_units_sold"}
        }
    },
    {
        "$sort": {
            "total_units_sold": -1
        }
    }
]

ranking_categoria = list(products.aggregate(pipeline_ranking_categoria))

for doc in ranking_categoria:
    doc["avg_price"] = round(doc["avg_price"], 2)
    doc["avg_rating"] = round(doc["avg_rating"], 2)
    print(doc)

# Aggregation pipeline con $lookup: productos + reviews

pipeline_producto_reviews = [
    {
        "$match": {
            "metrics.total_reviews": {"$gte": 5}
        }
    },
    {
        "$lookup": {
            "from": "reviews",
            "localField": "_id",
            "foreignField": "product_id",
            "as": "reviews_detail"
        }
    },
    {
        "$project": {
            "_id": 0,
            "name": 1,
            "category": 1,
            "price": 1,
            "reviews_summary": 1,
            "reviews_detail.rating": 1,
            "reviews_detail.comment": 1
        }
    },
    {
        "$limit": 3
    }
]

productos_con_reviews = list(products.aggregate(pipeline_producto_reviews))

for doc in productos_con_reviews:
    print(doc)

# Validación final del esquema

total_productos = products.count_documents({})
total_reviews = reviews.count_documents({})

producto_electronica = products.find_one({"category": "electronics"})
producto_hogar = products.find_one({"category": "home"})

print("============== VALIDACIÓN FINAL ==============")
print(f"Total productos insertados: {total_productos}")
print(f"Total reviews insertadas: {total_reviews}")
print("Producto electronics tiene specifications:", producto_electronica["specifications"])
print("Producto home tiene specifications:", producto_hogar["specifications"])
print("El esquema flexible permite diferentes estructuras por categoría.")
print("La colección reviews funciona como referencia externa.")
print("Las métricas precalculadas permiten consultas rápidas de catálogo.")
print("==============================================")